### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by pranavdeshai23** [shuowu/yi-note#67]
**Describe the bug**
When trying to send my notes to Google Docs, a pop-up window appears with a warning error - "Sign in with google temporarily disabled for this app."

**To Reproduce**
1. Click on 'Send notes to Google Docs'
2. Enter the mail id and password for my Google account
3. See error

**Expected behavior**
To be able to sign in and sync my notes to Google Docs

**Screenshots**
![image](https://user-images.githubusercontent.com/73290412/96869122-af107380-148c-11eb-9b3a-6cbcdd4e5cc3.png)

**Browser (please complete the following information):**
 - Chrome
 - Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by yeders** [comment]
also, the sync to onenote also is captured into a loop

**Comment by marciovenicio** [comment]
I'm having the same problem.

**Comment by shuowu** [comment]
Thanks for reporting the issue! I’ll look into a solution for it.

**Comment by SS2974** [comment]
> Thanks for reporting the issue! I’ll look into a solution for it.

Hi, the issue is still unresolved,

**Comment by yeders** [comment]
Yes, do you know if you're able to get onenote working?
I wasn't able to get onenote working.

Better yet, can I export it in markdown?

**Comment by shuowu** [comment]
@yeders The OneNote issue has been fixed in v1.5.4. It should be available in the chrome web store now.

**Comment by shuowu** [comment]
I submitted the google APIs OAuth consent for review, the google docs integration should be unblocked when the app is verified by google. The process would probably take 4- 6 weeks.

**Comment by SS2974** [comment]
Thanks for letting me know.

**Comment by cwendel16834** [comment]
Still an issue July 2021

**Comment by mike091020** [comment]
Still not working on August 21, 2021.  OneNote and Evernote export both work, however.  Great little project you've done here.  Bravo.

**Comment by dd1512** [comment]
Still not working as of 26 September. Great app btw
